"""Adiciona indices na tabela items

Revision ID: 03ee80d94e80
Revises: 
Create Date: 2025-09-22 08:53:17.597061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03ee80d94e80'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_items_created_at_operation_type', 'items', ['created_at', 'operation_type'], unique=False)
    op.create_index(op.f('ix_items_num_caixa'), 'items', ['num_caixa'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_num_caixa'), table_name='items')
    op.drop_index('ix_items_created_at_operation_type', table_name='items')
    # ### end Alembic commands ###
